

spring.servlet.multipart.enabled = true
spring.servlet.multipart.max-file-size =2GB
spring.servlet.multipart.max-request-size =2GB


server.tomcat.max-swallow-size = -1
server.tomcat.max-http-form-post-size = -1

file.upload.image-dir=uploads/images
file.upload-dir=./uploads

app.frontend.url=http://localhost:3000
app.cors.allowed-origins=http://localhost:3000