

spring.mail.port=587

spring.mail.host=smtp-relay.brevo.com
spring.mail.username=bb9a70001@smtp-brevo.com
app.mail.from=intisar19961@hotmail.com
spring.mail.password=${BREVO_SMTP_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000